In [1]:
! [ -d "numadic-customer-transaction-prediction" ] || wget https://nuws.co/datahack-dataset
![ -d "numadic-customer-transaction-prediction" ] || tar xvf datahack-dataset

In [2]:
!ls

datahack-dataset  numadic-customer-transaction-prediction  sample_data


In [3]:
from pathlib import Path
import numpy as np
from sklearn.preprocessing import StandardScaler
import pandas as pd

dir=Path("numadic-customer-transaction-prediction")
train_path=dir/"train.csv"
test_path=dir/"test.csv"

# Exploration

In [4]:
test_df=pd.read_csv(test_path)
df=pd.read_csv(train_path)
df.describe()

target          var_0  ...        var_198        var_199
count  200000.000000  200000.000000  ...  200000.000000  200000.000000
mean        0.100490      10.679914  ...      15.870720      -3.326537
std         0.300653       3.040051  ...       3.010945      10.438015
min         0.000000       0.408400  ...       6.299300     -38.852800
25%         0.000000       8.453850  ...      13.829700     -11.208475
50%         0.000000      10.524750  ...      15.934050      -2.819550
75%         0.000000      12.758200  ...      18.064725       4.836800
max         1.000000      20.315000  ...      26.079100      28.500700

[8 rows x 201 columns]

In [5]:
df.columns

Index(['ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4',
       'var_5', 'var_6', 'var_7',
       ...
       'var_190', 'var_191', 'var_192', 'var_193', 'var_194', 'var_195',
       'var_196', 'var_197', 'var_198', 'var_199'],
      dtype='object', length=202)

## Check for Nan 

In [6]:
for col in df:
    if df[col].isna().sum()!=0:
        print(col)

Hence the dataset contains no Na values


## Check for outliers

In [7]:
vars=df.drop(["ID_code","target"],axis=1)
var_cols=vars.columns # This will be useful moving forward

mx,mn=0,0
for col in vars.columns:
    if vars[col].max()>mx:
        mx=vars[col].max()
    if vars[col].min()<mn:
        mn=vars[col].min()
print(mx,mn) # Hence there dont seem to be any significant outliers

74.0321 -90.2525


There do not appear to be any outliers

## Check for label imbalance

In [8]:
df.target.value_counts()

0    179902
1     20098
Name: target, dtype: int64

Hence data is highly imbalanced. As can be seen above there are roughly 10 times more data points with the label being 0 than data points with the label being 1. 

# Preprocessing

### Addressing the label imbalance

If the imbalance is not addressed, metrics used to measure the efficacy of the model may become misleading. For eg. if the model always predicts the class with more occurence it would still have a very high accuracy

A naive solution would be to randomly sample the datapoints with target 0 till we have equal datapoints of both labels and discarding the remaining datapoints. 

This approach discards a large amount of potential information for the model to learn. Hence this approach won't be used.
To fix the imbalance Synthetic Minority Oversampling Technique(SMOTE) will be performed wherein the population of datapoints with label 1(lower number of datapoints) is randomly sampled and duplicated to increase number of datapoints with label 1.  

In [9]:
from imblearn.over_sampling import SMOTE
oversampler=SMOTE()
resampled_X,resampled_y=oversampler.fit_resample(df[var_cols],df['target'])


/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [10]:
np.unique(resampled_y,return_counts=True)

(array([0, 1]), array([179902, 179902]))

Now the number of datapoints with labels 1 and 0 are equal

### Scaling

In [11]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [12]:
scaler=MinMaxScaler()
scaler.fit(resampled_X)
scaled_X=scaler.transform(resampled_X)
scaled_Y=resampled_y.copy()

In [13]:
scaled_X.min(),scaled_X.max()

(0.0, 1.0000000000000002)

### Dimensionality Reduction

In [14]:
from sklearn.decomposition import PCA

In [15]:
variance_preserved=1.0 # Reduction only occurs only if variance_preserved <1.0
pca=PCA(n_components=variance_preserved,svd_solver="full")

if variance_preserved<1.0:
    reduced_X=pca.fit_transform(scaled_X)
else:
    reduced_X=scaled_X.copy()
reduced_Y=scaled_Y.copy()

In [16]:
scaled_X.shape, reduced_X.shape

((359804, 200), (359804, 200))

# Splitting Data



In [17]:
from sklearn.model_selection import train_test_split

In [20]:
trainX,testX, trainY,testY = train_test_split(
    reduced_X, reduced_Y, test_size=0.3, stratify=scaled_Y
)
input_size=trainX.shape[1]

# Model

In [21]:
from tensorflow.keras.layers import Dense,Input
import tensorflow as tf

In [34]:
initializer = tf.keras.initializers.HeNormal()
model=tf.keras.Sequential([
    Input(shape=(input_size,)),
    Dense(300,activation="relu",kernel_initializer=initializer),
    Dense(1000,activation="relu",kernel_initializer=initializer),
    Dense(500,activation="relu",kernel_initializer=initializer),
    Dense(40,activation="relu",kernel_initializer=initializer),
    Dense(1,activation="sigmoid")
])
lr=1e-3
opt=tf.keras.optimizers.Adam(learning_rate=lr)
loss="binary_crossentropy"
metrics=[tf.keras.metrics.BinaryAccuracy(),tf.keras.metrics.FalseNegatives(),tf.keras.metrics.FalsePositives()]

model.compile(optimizer=opt,loss=loss,metrics=metrics)

In [35]:
epochs=4
batch_size=100
verbose=2
model.fit(x=trainX,y=trainY,epochs=epochs,batch_size=batch_size,validation_data=(testX,testY),verbose=verbose)

Epoch 1/4
2519/2519 - 45s - loss: 0.4076 - binary_accuracy: 0.8139 - false_negatives_3: 23185.0000 - false_positives: 23690.0000 - val_loss: 0.3664 - val_binary_accuracy: 0.8393 - val_false_negatives_3: 7246.0000 - val_false_positives: 10098.0000
Epoch 2/4
2519/2519 - 44s - loss: 0.3687 - binary_accuracy: 0.8388 - false_negatives_3: 20889.0000 - false_positives: 19721.0000 - val_loss: 0.3542 - val_binary_accuracy: 0.8456 - val_false_negatives_3: 5971.0000 - val_false_positives: 10696.0000
Epoch 3/4
2519/2519 - 44s - loss: 0.3551 - binary_accuracy: 0.8456 - false_negatives_3: 19798.0000 - false_positives: 19084.0000 - val_loss: 0.3584 - val_binary_accuracy: 0.8456 - val_false_negatives_3: 6531.0000 - val_false_positives: 10135.0000
Epoch 4/4
2519/2519 - 44s - loss: 0.3406 - binary_accuracy: 0.8519 - false_negatives_3: 19007.0000 - false_positives: 18286.0000 - val_loss: 0.3318 - val_binary_accuracy: 0.8575 - val_false_negatives_3: 7232.0000 - val_false_positives: 8150.0000


In [36]:
preds=model.predict(testX)
tf.math.round(preds)

<tf.Tensor: shape=(107942, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [1.],
       ...,
       [1.],
       [0.],
       [1.]], dtype=float32)>

In [37]:
tf.math.confusion_matrix(testY,tf.math.round(preds))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[45821,  8150],
       [ 7232, 46739]], dtype=int32)>

# Predicting on Test dataset

In [39]:
inputs=test_df[var_cols]
inputs=scaler.transform(inputs) # Scaling with same scaler
output=tf.math.round(model.predict(inputs))
output=np.array(output).squeeze()

In [40]:
test_df["target"]=pd.Series(output)
test_df.head(10)

ID_code    var_0    var_1    var_2  ...  var_197  var_198  var_199  target
0  test_0  11.0656   7.7798  12.9536  ...  10.7200  15.4722  -8.7197     0.0
1  test_1   8.5304   1.2543  11.3047  ...   9.8714  19.1293 -20.9760     1.0
2  test_2   5.4827 -10.3581  10.1407  ...   7.0618  19.8956 -23.1794     0.0
3  test_3   8.5374  -1.3222  12.0220  ...   9.2295  13.0168  -4.2108     0.0
4  test_4  11.7058  -0.1327  14.1295  ...   7.2882  13.9260  -9.1846     0.0
5  test_5   5.9862  -2.2913   8.6058  ...   9.8117  17.1127  10.8240     0.0
6  test_6   8.4624  -6.1065   7.3603  ...   9.1509  18.4736   5.1499     0.0
7  test_7  17.3035  -2.4212  13.3989  ...  10.4855  23.4631   0.7283     1.0
8  test_8   6.9856   0.8402  13.7161  ...   9.9207  16.9865  -3.3304     0.0
9  test_9  10.3811  -6.9348  14.6690  ...   9.5788  15.8146   9.3457     0.0

[10 rows x 202 columns]

In [41]:
output_df=test_df[["ID_code","target"]]
output_df.to_csv("submission.csv")